"""Observable transition verifier for recovery-aware PSSE agents."""

from .dataset import (
    build_transition_dataset,
    build_verifier_dataset,
    build_verifier_example,
    dataset_statistics,
    extract_transition_labels,
    load_jsonl,
    split_dataset,
    transition_from_dagger_example,
    write_jsonl,
)
from .evaluate import (
    classification_metrics,
    evaluate_predictions,
    evaluate_verifier,
    expected_calibration_error,
    false_accept_final_rate,
    next_action_validity_precision,
)
from .features import (
    FEATURE_NAMES,
    PRIVILEGED_FIELDS,
    TransitionFeatureExtractor,
    TransitionInput,
    extract_features,
    extract_transition_features,
    feature_vector,
    normalize_transition,
    observable_copy,
    observable_verification_metrics,
)
from .model import HybridProcessVerifier, LinearVerifierModel, StructuredVerifierModel
from .rules import (
    DISPOSITIONS,
    DeterministicProcessVerifier,
    RuleBasedVerifier,
    RuleConfig,
    VerifierDecision,
    verify_transition,
)

__all__ = [
    "DISPOSITIONS",
    "FEATURE_NAMES",
    "PRIVILEGED_FIELDS",
    "DeterministicProcessVerifier",
    "HybridProcessVerifier",
    "LinearVerifierModel",
    "RuleBasedVerifier",
    "RuleConfig",
    "StructuredVerifierModel",
    "TransitionFeatureExtractor",
    "TransitionInput",
    "VerifierDecision",
    "build_transition_dataset",
    "build_verifier_dataset",
    "build_verifier_example",
    "classification_metrics",
    "dataset_statistics",
    "evaluate_predictions",
    "evaluate_verifier",
    "expected_calibration_error",
    "extract_features",
    "extract_transition_features",
    "extract_transition_labels",
    "false_accept_final_rate",
    "feature_vector",
    "load_jsonl",
    "next_action_validity_precision",
    "normalize_transition",
    "observable_copy",
    "observable_verification_metrics",
    "split_dataset",
    "transition_from_dagger_example",
    "verify_transition",
    "write_jsonl",
]
