"""Deterministically build the frozen BC0 closed-loop evaluation suite.

The release artifact is intentionally derived only from repository-tracked
inputs.  In particular, the builder selects the tracked 17-root HIF fallback
explicitly instead of allowing ignored benchmark directories in a developer
checkout to change the generated bytes.
"""

from __future__ import annotations

import argparse
import copy
import importlib.metadata
import json
import os
import platform
import subprocess
import tempfile
from collections import Counter, defaultdict
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import Any

from mcp_server.matpower_server import _load_python_case

from psse_env.dagger.evaluator import (
    EVALUATION_SUITES,
    fingerprint_evaluation_suites,
    validate_release_scenario_suites,
)
from psse_env.dagger.splits import physical_root_fingerprint
from psse_env.actions import (
    COMMIT_STATE,
    CORRECT_MEASUREMENTS,
    GET_MEASUREMENT_CONTEXT,
    RUN_WLS,
    invalid_action,
)
from psse_env.providers.scenario_generator import (
    DEFAULT_BALANCED_ARTIFACT_DIR,
    DEFAULT_CORPUS_PATH,
    DEFAULT_HIF_FALLBACK_SAMPLE_PATHS,
    DEFAULT_IMBALANCE_SAMPLE_PATH,
    Round0ScenarioGenerator,
    ScenarioRejected,
)
from psse_env.sft.provenance import file_sha256, stable_json_sha256


# The evaluator seed is part of the BC0 release protocol. Scenario
# construction deliberately uses a different deterministic seed for ordering.
# Independence from the round-0 aggregate is structural: shared tabular
# corpus rows are assigned to the complementary ``evaluation`` physical-source
# partition, while aggregate generation uses ``train``.
BC0_SUITE_SEED = 20260719
BC0_SUITE_GENERATION_SEED = 20260734
BC0_SUITE_MAX_STEPS = 24
BC0_SUITE_SCHEMA_VERSION = 1
BC0_SUITE_SPLIT = "release_eval"
BC0_SUITE_SOURCE_PARTITION = "evaluation"
BC0_BUILDER_PYTHON_MAJOR_MINOR = (3, 12)
BC0_BUILDER_PACKAGE_VERSIONS = {
    "numpy": "2.3.5",
    "scipy": "1.16.3",
    "PYPOWER": "5.1.19",
    "fastmcp": "2.12.4",
    # Aggregate HIF diagnostics execute OpenDSS in this same reviewed
    # environment.  Pin both the public package and its exact native runtime
    # chain so a missing or drifted solver cannot be misreported as a valid
    # diagnostic rejection.
    "OpenDSSDirect.py": "0.9.4",
    "dss-python": "0.15.7",
    "dss-python-backend": "0.14.5",
}
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_POLICY_PATH = Path(__file__).with_name("bc0_evaluation_policy.json")
DEFAULT_OUTPUT_PATH = Path(__file__).with_name("suites") / "bc0_eval_suite_v1.json"
_FIXED_SOURCE_INPUTS = (
    Path(DEFAULT_CORPUS_PATH),
    Path(DEFAULT_HIF_FALLBACK_SAMPLE_PATHS[0]),
    REPO_ROOT / "mcp_server" / "case14.m",
)

# BC0 freezes ten round-0 release-policy families. Three-phase unbalance and
# telemetry-no-disturbance remain generator capabilities, but are explicit
# scope exclusions until a future policy supplies reviewed quotas, outcome
# semantics, and thresholds. This is not a correction-capability distinction:
# the selected harmonic and HIF families are diagnosis-only as well.
BC0_RELEASE_FAMILIES = frozenset(
    {
        "no_error",
        "measurement",
        "multi_measurement",
        "parameter",
        "topology",
        "harmonic",
        "hif",
        "measurement+parameter",
        "measurement+topology",
        "measurement+hif",
    }
)

# Every root is assigned once.  Row sums equal the ten family-policy minima
# (115 roots total).  The efficiency suite deliberately mixes the diagnostic
# families with core state-estimation families so checkpoint promotion bounds
# tool-call efficiency for mixed-error recovery, not only HIF/harmonic
# diagnosis.
BC0_SUITE_FAMILY_QUOTAS: dict[str, dict[str, int]] = {
    "standard_success": {
        "no_error": 4,
        "parameter": 3,
        "topology": 3,
        "multi_measurement": 4,
        "measurement+parameter": 4,
        "measurement+topology": 3,
    },
    "forced_error_recovery": {
        "multi_measurement": 7,
        "measurement+parameter": 7,
        "measurement+topology": 7,
    },
    "partial_success_retention": {
        "multi_measurement": 7,
        "measurement+parameter": 7,
        "measurement+topology": 7,
    },
    "invalid_action_recovery": {
        "measurement": 6,
        "parameter": 3,
        "topology": 3,
        "harmonic": 2,
        "multi_measurement": 2,
        "measurement+parameter": 2,
        "measurement+topology": 3,
    },
    "efficiency": {
        "hif": 17,
        "measurement+hif": 2,
        "harmonic": 2,
        "measurement": 2,
        "parameter": 2,
        "topology": 2,
        "measurement+parameter": 2,
        "measurement+topology": 2,
    },
}


def _repo_relative(path: Path) -> str:
    try:
        return str(path.absolute().relative_to(REPO_ROOT.absolute()))
    except ValueError as exc:
        raise ValueError(f"release-suite input is outside the repository: {path}") from exc


def _has_symlink_component(path: Path) -> bool:
    relative = path.absolute().relative_to(REPO_ROOT.absolute())
    current = REPO_ROOT.absolute()
    for component in relative.parts:
        current /= component
        if current.is_symlink():
            return True
    return False


def _git_output(*args: str) -> bytes:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", b"")
        message = detail.decode("utf-8", errors="replace").strip()
        raise RuntimeError(
            "release-suite construction requires an intact Git checkout"
            + (f": {message}" if message else "")
        ) from exc
    return completed.stdout


def _tracked_release_inputs() -> set[Path]:
    """Return the clean tracked inputs eligible to influence suite bytes.

    The balanced artifact directory is ignored for newly generated files, so
    resolving a referenced basename directly from the worktree would let an
    ignored developer artifact change root selection.  This allowlist is read
    from Git and dirty tracked inputs are rejected before generation.
    """

    balanced_relative = _repo_relative(
        Path(DEFAULT_BALANCED_ARTIFACT_DIR) / "cases_parameter_error"
    )
    fixed_relative = [_repo_relative(path) for path in _FIXED_SOURCE_INPUTS]
    raw = _git_output(
        "ls-files",
        "-z",
        "--",
        *fixed_relative,
        balanced_relative,
    )
    tracked_relative = {
        item.decode("utf-8") for item in raw.split(b"\0") if item
    }
    missing_fixed = sorted(set(fixed_relative) - tracked_relative)
    if missing_fixed:
        raise RuntimeError(
            "release-suite fixed inputs are not tracked: " + ", ".join(missing_fixed)
        )
    tracked_paths = {REPO_ROOT / item for item in tracked_relative}
    missing_paths = sorted(
        _repo_relative(path) for path in tracked_paths if not path.is_file()
    )
    if missing_paths:
        raise RuntimeError(
            "release-suite tracked inputs are missing: " + ", ".join(missing_paths)
        )
    symlinks = sorted(
        _repo_relative(path) for path in tracked_paths if _has_symlink_component(path)
    )
    if symlinks:
        raise RuntimeError(
            "release-suite inputs must not be symlinks: " + ", ".join(symlinks)
        )
    dirty = _git_output(
        "diff",
        "--name-only",
        "-z",
        "HEAD",
        "--",
        *fixed_relative,
        balanced_relative,
    )
    dirty_relative = sorted(
        item.decode("utf-8") for item in dirty.split(b"\0") if item
    )
    if dirty_relative:
        raise RuntimeError(
            "release-suite inputs differ from HEAD: " + ", ".join(dirty_relative)
        )
    return {path.absolute() for path in tracked_paths}


class _TrackedArtifactScenarioGenerator(Round0ScenarioGenerator):
    """Round-0 generator that cannot resolve ignored artifact shadows."""

    def __init__(self, *args: Any, tracked_inputs: set[Path], **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._tracked_inputs = set(tracked_inputs)
        self.consumed_artifacts: set[Path] = set()

    def _local_artifact(self, referenced_path: str, subdir: str) -> Path:
        basename = os.path.basename(str(referenced_path).replace("\\", "/"))
        local = (self.balanced_artifact_dir / subdir / basename).absolute()
        if _has_symlink_component(local):
            raise ScenarioRejected("artifact_missing", str(local))
        if local not in self._tracked_inputs or not local.is_file():
            raise ScenarioRejected("artifact_missing", str(local))
        self.consumed_artifacts.add(local)
        return local


def canonical_json_bytes(value: Any) -> bytes:
    """Return the stable, human-reviewable representation used on disk."""

    return (
        json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False)
        + "\n"
    ).encode("utf-8")


def _builder_environment_descriptor() -> dict[str, Any]:
    """Return version-only provenance for the numerical build environment.

    This descriptor is emitted in the rebuild report, not serialized into the
    frozen suite.  Deliberately omitting host, platform, path, and compiler
    details keeps ``--check`` a byte-for-byte content check across machines.
    """

    packages: dict[str, str | None] = {}
    for distribution in BC0_BUILDER_PACKAGE_VERSIONS:
        try:
            packages[distribution] = importlib.metadata.version(distribution)
        except importlib.metadata.PackageNotFoundError:
            packages[distribution] = None
    return {
        "python_version": platform.python_version(),
        "packages": packages,
    }


def _opendss_runtime_version() -> str:
    """Load the pinned native OpenDSS engine and return its version banner."""

    try:
        import opendssdirect as dss  # type: ignore

        version_banner = str(dss.Basic.Version()).strip()
    except Exception as exc:
        raise RuntimeError(
            "OpenDSSDirect native runtime could not be loaded: "
            f"{type(exc).__name__}: {exc}"
        ) from exc
    required_markers = (
        f"DSS C-API Library version {BC0_BUILDER_PACKAGE_VERSIONS['dss-python-backend']}",
        f"DSS-Python version: {BC0_BUILDER_PACKAGE_VERSIONS['dss-python']}",
        f"OpenDSSDirect.py version: {BC0_BUILDER_PACKAGE_VERSIONS['OpenDSSDirect.py']}",
    )
    missing = [marker for marker in required_markers if marker not in version_banner]
    if missing:
        raise RuntimeError(
            "OpenDSSDirect native runtime version mismatch: missing "
            + ", ".join(repr(marker) for marker in missing)
        )
    return version_banner


def validate_builder_environment() -> dict[str, Any]:
    """Validate and return the approved BC0 release-build environment.

    Python patch releases are recorded but the release contract is the
    documented 3.12 major/minor. Numerical and directly imported builder
    distributions are exact-pinned because they can affect generated bytes or
    whether the deterministic MATPOWER parser can be imported.
    """

    observed = _builder_environment_descriptor()
    failures: list[str] = []

    raw_python = observed.get("python_version")
    try:
        python_major_minor = tuple(
            int(component) for component in str(raw_python).split(".")[:2]
        )
    except ValueError:
        python_major_minor = ()
    if python_major_minor != BC0_BUILDER_PYTHON_MAJOR_MINOR:
        expected = ".".join(str(value) for value in BC0_BUILDER_PYTHON_MAJOR_MINOR)
        failures.append(f"Python {raw_python!r} (required {expected}.x)")

    raw_packages = observed.get("packages")
    packages = raw_packages if isinstance(raw_packages, Mapping) else {}
    for distribution, expected in BC0_BUILDER_PACKAGE_VERSIONS.items():
        actual = packages.get(distribution)
        if actual != expected:
            failures.append(
                f"{distribution} {actual!r} (required {expected})"
            )

    try:
        _opendss_runtime_version()
    except RuntimeError as exc:
        failures.append(str(exc))

    if failures:
        raise RuntimeError(
            "BC0 release-suite builder environment is not approved: "
            + "; ".join(failures)
        )
    return observed


def _json_native(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {
            str(key): _json_native(item)
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        }
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return [_json_native(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if callable(getattr(value, "tolist", None)):
        return _json_native(value.tolist())
    if callable(getattr(value, "item", None)):
        return _json_native(value.item())
    return copy.deepcopy(value)


def _portable_case_reference(value: Any) -> Any:
    """Embed non-built-in MATPOWER cases so the suite has no absolute paths."""

    if isinstance(value, Mapping):
        return _json_native(value)
    if value == "case14":
        return "case14"
    if not isinstance(value, (str, os.PathLike)):
        raise ValueError(f"unsupported clean-case reference: {type(value).__name__}")
    path = Path(value)
    if not path.is_file():
        candidate = REPO_ROOT / path
        if candidate.is_file():
            path = candidate
        else:
            raise ValueError(f"clean-case file does not exist: {value}")
    return _json_native(_load_python_case(str(path)))


def family_plan_from_policy(
    policy_path: str | os.PathLike[str] = DEFAULT_POLICY_PATH,
) -> dict[str, int]:
    payload = json.loads(Path(policy_path).read_text(encoding="utf-8"))
    family_policy = payload.get("family_policy")
    if not isinstance(family_policy, Mapping):
        raise ValueError("evaluation policy family_policy is missing")
    plan: dict[str, int] = {}
    for family, contract in family_policy.items():
        if not isinstance(contract, Mapping):
            raise ValueError(f"family_policy.{family} must be a mapping")
        minimum = contract.get("minimum_physical_roots")
        if isinstance(minimum, bool) or not isinstance(minimum, int) or minimum <= 0:
            raise ValueError(
                f"family_policy.{family}.minimum_physical_roots must be positive"
            )
        plan[str(family)] = minimum
    expected = set(BC0_RELEASE_FAMILIES)
    if set(plan) != expected:
        raise ValueError(
            "suite family plan disagrees with scenario generator: "
            f"missing={sorted(expected - set(plan))}, extra={sorted(set(plan) - expected)}"
        )
    return dict(sorted(plan.items()))


def validate_quota_matrix(
    plan: Mapping[str, int],
    quotas: Mapping[str, Mapping[str, int]] = BC0_SUITE_FAMILY_QUOTAS,
    *,
    minimum_roots_per_suite: int = 20,
) -> None:
    if set(quotas) != set(EVALUATION_SUITES):
        raise ValueError("suite quota matrix must contain exactly the five release suites")
    allocated: Counter[str] = Counter()
    for suite in EVALUATION_SUITES:
        rows = quotas[suite]
        total = 0
        for family, raw_count in rows.items():
            if family not in plan:
                raise ValueError(f"suite {suite} references unknown family {family}")
            if isinstance(raw_count, bool) or not isinstance(raw_count, int) or raw_count < 0:
                raise ValueError(f"suite quota {suite}.{family} must be non-negative")
            allocated[family] += raw_count
            total += raw_count
        if total < minimum_roots_per_suite:
            raise ValueError(
                f"suite {suite} has {total} roots, below {minimum_roots_per_suite}"
            )
    if dict(sorted(allocated.items())) != dict(sorted(plan.items())):
        raise ValueError(
            "suite quota family totals disagree with policy minima: "
            f"allocated={dict(sorted(allocated.items()))}, plan={dict(sorted(plan.items()))}"
        )


def _truth_payload(scenario: Mapping[str, Any]) -> dict[str, Any]:
    truth: dict[str, Any] = {}
    hidden = scenario.get("hidden_truth")
    if hidden is not None and not isinstance(hidden, Mapping):
        raise ValueError("scenario hidden_truth must be a mapping")
    for source in (hidden or {}, scenario):
        for key, value in source.items():
            normalized = str(key)
            if normalized.startswith("true_") or normalized in {
                "clean_case",
                "clean_measurements",
                "clean_state",
                "remaining_true_faults",
                "remaining_true_fault_count",
            }:
                copied = _portable_case_reference(value) if normalized == "clean_case" else _json_native(value)
                if normalized in truth and truth[normalized] != copied:
                    raise ValueError(f"conflicting truth value for {normalized}")
                truth[normalized] = copied
    truth["truth_complete"] = True
    return truth


def _execution_metadata(scenario: Mapping[str, Any]) -> dict[str, Any] | None:
    """Return runtime metadata with corpus-only evaluation labels removed.

    The tracked HIF rows contain ``z_clean`` vectors used when validating the
    corpus and ``detected*`` flags computed against the injected fault.  The
    deployment estimators consume observed scans and ranked diagnostic output,
    not either label, so neither belongs in ``env.reset``.
    """

    raw = scenario.get("metadata")
    if raw is None:
        return None
    if not isinstance(raw, Mapping):
        raise ValueError("scenario metadata must be a mapping")
    metadata = _json_native(raw)

    scan_window = metadata.get("hif_scan_window")
    if isinstance(scan_window, Mapping):
        scans = scan_window.get("scans")
        if isinstance(scans, list):
            for scan in scans:
                if isinstance(scan, dict):
                    scan.pop("z_clean", None)

    diagnostic = metadata.get("nlm_diagnostic")
    if isinstance(diagnostic, dict):
        for key in ("detected", "detected_top1", "detected_top3"):
            diagnostic.pop(key, None)
    return metadata


def partition_release_scenario_v1(
    scenario: Mapping[str, Any],
    *,
    split: str = BC0_SUITE_SPLIT,
) -> dict[str, Any]:
    """Convert one validated generator row into the release-only envelope."""

    scenario_id = str(scenario.get("scenario_id") or "").strip()
    if not scenario_id:
        raise ValueError("scenario_id is required")
    family = str(scenario.get("scenario_family") or "").strip()
    if not family:
        raise ValueError("scenario_family is required")
    cardinality = scenario.get("error_cardinality")
    if isinstance(cardinality, bool) or not isinstance(cardinality, int) or cardinality < 0:
        raise ValueError("error_cardinality must be a non-negative integer")

    execution: dict[str, Any] = {
        "scenario_id": scenario_id,
        "case": _json_native(scenario.get("case")),
        "measurements": _json_native(scenario.get("measurements")),
    }
    metadata = _execution_metadata(scenario)
    if metadata is not None:
        execution["metadata"] = metadata
    for key in (
        "semantic_field_provenance",
        "unresolved_signatures",
        "remaining_anomaly_score",
        "no_material_anomaly_remaining",
        "requires_measurement_context",
    ):
        if key in scenario:
            execution[key] = _json_native(scenario[key])

    truth = _truth_payload(scenario)
    audit: dict[str, Any] = {
        "truth": truth,
        # A standalone partition is a standard-success scenario until the
        # allocator binds it to one of the five exact suite contracts.
        "evaluation_intervention": {
            "intervention_schema_version": 1,
            "kind": "none",
        },
    }
    if "release_audit" in scenario:
        audit["release_audit"] = _json_native(scenario["release_audit"])

    # Fingerprint the generator row before the execution/audit partition strips
    # offline-only metadata or embeds a derived case. The release aggregate
    # fingerprints the same source representation, so scenario IDs and
    # serialization details cannot conceal a reused physical realization.
    fingerprint = physical_root_fingerprint(scenario)
    grouping = {
        "root_scenario_id": str(scenario.get("root_scenario_id") or scenario_id),
        "physical_root_fingerprint": fingerprint,
        "scenario_family": family,
        "error_cardinality": cardinality,
        "case_id": str(scenario.get("network_case") or scenario.get("case") or ""),
        "split": str(split),
        "source_tier": str(scenario.get("source_tier") or ""),
    }
    envelope = {
        "scenario_schema_version": BC0_SUITE_SCHEMA_VERSION,
        "execution": execution,
        "audit": audit,
        "grouping": grouping,
    }
    validate_release_scenario_suites({"standard_success": [envelope]})
    return envelope


def _partial_setup_actions(scenario: Mapping[str, Any]) -> list[dict[str, Any]]:
    audit = scenario.get("audit")
    audit = audit if isinstance(audit, Mapping) else {}
    truth = audit.get("truth")
    truth = truth if isinstance(truth, Mapping) else {}
    measurement_errors = truth.get("true_measurement_errors")
    if not isinstance(measurement_errors, Sequence) or isinstance(
        measurement_errors, (str, bytes)
    ) or not measurement_errors:
        raise ValueError("partial-success scenario needs measurement truth")
    first = measurement_errors[0]
    if not isinstance(first, Mapping):
        raise ValueError("partial-success measurement truth must be a mapping")
    index = first.get("index")
    clean = first.get("clean")
    if isinstance(index, bool) or not isinstance(index, int) or index < 0:
        raise ValueError("partial-success measurement index is invalid")
    if clean is None:
        raise ValueError("partial-success measurement clean value is missing")
    return [
        {
            "tool": GET_MEASUREMENT_CONTEXT,
            "arguments": {"state_id": "$active"},
        },
        {
            "tool": CORRECT_MEASUREMENTS,
            "arguments": {
                "state_id": "$active",
                "measurement_updates": {str(index): float(clean)},
            },
        },
        {"tool": RUN_WLS, "arguments": {"state_id": "$candidate"}},
        {
            "tool": COMMIT_STATE,
            "arguments": {"candidate_state_id": "$candidate"},
        },
    ]


def _intervention_for_suite(
    suite: str, scenario: Mapping[str, Any]
) -> dict[str, Any]:
    """Return the immutable semantics marker consumed by the evaluator.

    The evaluator owns execution and audit of these instructions.  Keeping the
    marker in the audit partition prevents it from entering ``env.reset`` or a
    policy observation.
    """

    if suite == "standard_success":
        return {"intervention_schema_version": 1, "kind": "none"}
    if suite == "forced_error_recovery":
        return {
            "intervention_schema_version": 1,
            "kind": "pre_policy_failure",
            "failure_mode": "well_formed",
            "error_code": "injected_transient_tool_failure",
        }
    if suite == "invalid_action_recovery":
        return {
            "intervention_schema_version": 1,
            "kind": "pre_policy_failure",
            "failure_mode": "malformed",
            "error_code": "injected_invalid_action",
        }
    if suite == "partial_success_retention":
        return {
            "intervention_schema_version": 1,
            "kind": "committed_partial_correction",
            "setup_actions": _partial_setup_actions(scenario),
            "retention_required": True,
        }
    if suite == "efficiency":
        return {
            "intervention_schema_version": 1,
            "kind": "efficiency_budget",
            "limits": {
                "maximum_policy_steps": BC0_SUITE_MAX_STEPS,
                "maximum_wls_calls": 6,
                "maximum_specialized_tool_calls": 4,
            },
        }
    raise ValueError(f"unsupported release suite: {suite}")


class _PartialSetupProbePolicy:
    def act(self, observation: Mapping[str, Any]) -> dict[str, Any]:
        del observation
        return invalid_action("partial_setup_probe_complete")


def _production_partial_setup_validator() -> Callable[[Mapping[str, Any]], bool]:
    """Return an exact production probe for the partial-retention prelude."""

    from psse_env.dagger.evaluator import ClosedLoopRolloutEvaluator
    from psse_env.dagger.release_factories import (
        deterministic_case_loader,
        production_environment_factory,
    )

    def policy_factory(**kwargs: Any) -> _PartialSetupProbePolicy:
        del kwargs
        return _PartialSetupProbePolicy()

    evaluator = ClosedLoopRolloutEvaluator(
        env_factory=production_environment_factory,
        policy_factory=policy_factory,
        max_steps=1,
        seed=BC0_SUITE_SEED,
        case_loader=deterministic_case_loader,
        required_suites=("partial_success_retention",),
        minimum_suites=1,
        minimum_episodes_per_suite=1,
        minimum_roots_per_suite=1,
        require_release_environment=True,
    )

    def validate(source: Mapping[str, Any]) -> bool:
        row = copy.deepcopy(dict(source))
        row["audit"]["evaluation_intervention"] = _intervention_for_suite(
            "partial_success_retention", row
        )
        try:
            evaluator.evaluate({"partial_success_retention": [row]})
        except ValueError as exc:
            if str(exc).startswith(
                "partial setup commit requires ACCEPT_PARTIAL oracle disposition:"
            ):
                return False
            raise
        return True

    return validate


def allocate_suite_roots(
    scenarios: Sequence[Mapping[str, Any]],
    *,
    plan: Mapping[str, int],
    quotas: Mapping[str, Mapping[str, int]] = BC0_SUITE_FAMILY_QUOTAS,
    partial_setup_validator: Callable[[Mapping[str, Any]], bool] | None = None,
) -> dict[str, list[dict[str, Any]]]:
    validate_quota_matrix(plan, quotas)
    by_family: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for scenario in scenarios:
        envelope = partition_release_scenario_v1(scenario)
        by_family[envelope["grouping"]["scenario_family"]].append(envelope)
    for rows in by_family.values():
        rows.sort(key=lambda row: row["execution"]["scenario_id"])
    observed = {family: len(rows) for family, rows in sorted(by_family.items())}
    if observed != dict(sorted(plan.items())):
        raise ValueError(
            f"generator did not meet the frozen family plan: observed={observed}, plan={dict(sorted(plan.items()))}"
        )

    partial_reserved: dict[str, list[dict[str, Any]]] = {}
    reserved_roots: set[str] = set()
    if partial_setup_validator is not None:
        for family, count in sorted(
            quotas["partial_success_retention"].items()
        ):
            selected = []
            for row in by_family[family]:
                if partial_setup_validator(row):
                    selected.append(row)
                if len(selected) == count:
                    break
            if len(selected) != count:
                raise ValueError(
                    "insufficient admissible partial-success roots for "
                    f"{family}: required={count}, observed={len(selected)}"
                )
            partial_reserved[family] = selected
            reserved_roots.update(
                row["grouping"]["physical_root_fingerprint"] for row in selected
            )

    used_roots: set[str] = set()
    suites: dict[str, list[dict[str, Any]]] = {name: [] for name in EVALUATION_SUITES}
    for suite in EVALUATION_SUITES:
        for family, count in sorted(quotas[suite].items()):
            if suite == "partial_success_retention" and partial_setup_validator is not None:
                selected = partial_reserved[family]
            else:
                selected = [
                    row
                    for row in by_family[family]
                    if row["grouping"]["physical_root_fingerprint"] not in used_roots
                    and (
                        partial_setup_validator is None
                        or row["grouping"]["physical_root_fingerprint"]
                        not in reserved_roots
                    )
                ][:count]
            if len(selected) != count:
                raise ValueError(f"insufficient {family} roots for suite {suite}")
            for source in selected:
                row = copy.deepcopy(source)
                row["audit"]["evaluation_intervention"] = _intervention_for_suite(
                    suite, row
                )
                suites[suite].append(row)
                used_roots.add(row["grouping"]["physical_root_fingerprint"])
        suites[suite].sort(key=lambda row: row["execution"]["scenario_id"])

    roots = [
        row["grouping"]["physical_root_fingerprint"]
        for suite in EVALUATION_SUITES
        for row in suites[suite]
    ]
    if len(roots) != len(set(roots)):
        duplicates = sorted(root for root, count in Counter(roots).items() if count > 1)
        raise ValueError(f"physical roots are not globally unique: {duplicates[:8]}")
    validate_release_scenario_suites(suites)
    fingerprint_evaluation_suites(
        suites,
        seed=BC0_SUITE_SEED,
        required_suites=EVALUATION_SUITES,
        minimum_suites=len(EVALUATION_SUITES),
        minimum_episodes_per_suite=1,
        minimum_roots_per_suite={name: 20 for name in EVALUATION_SUITES},
    )
    return suites


def build_bc0_suite(
    *,
    policy_path: str | os.PathLike[str] = DEFAULT_POLICY_PATH,
    seed: int = BC0_SUITE_GENERATION_SEED,
    validate_physics: bool = True,
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any]]:
    if int(seed) != BC0_SUITE_GENERATION_SEED:
        raise ValueError(
            "BC0 release suite generation seed must be "
            f"{BC0_SUITE_GENERATION_SEED}"
        )
    builder_environment = validate_builder_environment()
    plan = family_plan_from_policy(policy_path)
    validate_quota_matrix(plan)
    tracked_inputs = _tracked_release_inputs()
    with tempfile.TemporaryDirectory(prefix="bc0_suite_cases_") as case_directory:
        generator = _TrackedArtifactScenarioGenerator(
            corpus_path=DEFAULT_CORPUS_PATH,
            hif_sample_paths=DEFAULT_HIF_FALLBACK_SAMPLE_PATHS,
            imbalance_sample_path=DEFAULT_IMBALANCE_SAMPLE_PATH,
            balanced_artifact_dir=DEFAULT_BALANCED_ARTIFACT_DIR,
            derived_case_dir=case_directory,
            seed=seed,
            validate=validate_physics,
            source_partition=BC0_SUITE_SOURCE_PARTITION,
            tracked_inputs=tracked_inputs,
        )
        generated = generator.build(plan)
        suites = allocate_suite_roots(
            generated,
            plan=plan,
            partial_setup_validator=_production_partial_setup_validator(),
        )
        report = generator.report()
        consumed_inputs = set(_FIXED_SOURCE_INPUTS) | generator.consumed_artifacts
    report = {
        **report,
        "builder_environment": builder_environment,
        "evaluation_seed": BC0_SUITE_SEED,
        "suite_counts": {name: len(suites[name]) for name in EVALUATION_SUITES},
        "total_roots": sum(len(rows) for rows in suites.values()),
        "family_plan_sha256": stable_json_sha256(dict(sorted(plan.items()))),
        "source_inputs": {
            _repo_relative(path): file_sha256(path)
            for path in sorted(consumed_inputs, key=_repo_relative)
        },
    }
    return suites, report


def write_frozen_suite(
    output_path: str | os.PathLike[str] = DEFAULT_OUTPUT_PATH,
    *,
    check: bool = False,
    validate_physics: bool = True,
) -> dict[str, Any]:
    suites, report = build_bc0_suite(validate_physics=validate_physics)
    serialized = canonical_json_bytes(suites)
    output = Path(output_path)
    if check:
        if not output.is_file() or output.read_bytes() != serialized:
            raise RuntimeError(f"frozen suite differs from deterministic rebuild: {output}")
        return {**report, "output": str(output), "sha256": file_sha256(output)}
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", suffix=".tmp", dir=str(output.parent)
    )
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(serialized)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, output)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)
    return {**report, "output": str(output), "sha256": file_sha256(output)}


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT_PATH))
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--skip-physics-validation",
        action="store_true",
        help="Development tests only; never use for the frozen release artifact.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    report = write_frozen_suite(
        args.output,
        check=args.check,
        validate_physics=not args.skip_physics_validation,
    )
    print(json.dumps(report, indent=2, sort_keys=True, allow_nan=False))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "BC0_SUITE_FAMILY_QUOTAS",
    "BC0_RELEASE_FAMILIES",
    "BC0_SUITE_GENERATION_SEED",
    "BC0_BUILDER_PACKAGE_VERSIONS",
    "BC0_BUILDER_PYTHON_MAJOR_MINOR",
    "BC0_SUITE_MAX_STEPS",
    "BC0_SUITE_SEED",
    "BC0_SUITE_SOURCE_PARTITION",
    "DEFAULT_OUTPUT_PATH",
    "allocate_suite_roots",
    "build_bc0_suite",
    "canonical_json_bytes",
    "family_plan_from_policy",
    "partition_release_scenario_v1",
    "validate_quota_matrix",
    "validate_builder_environment",
    "write_frozen_suite",
]
