"""Reproducibility metadata for live tokenizer and SFT gates."""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any, Mapping, Sequence


def stable_json_sha256(value: Any) -> str:
    payload = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def file_sha256(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def git_source_state(repo_root: str | Path) -> dict[str, Any]:
    """Return the exact source commit and whether local edits affected the gate."""
    root = Path(repo_root)
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        tracked_diff = subprocess.run(
            ["git", "diff", "--binary", "--no-ext-diff", "HEAD", "--"],
            cwd=root,
            check=True,
            capture_output=True,
        ).stdout
        untracked_status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=all"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.splitlines()
    except (OSError, subprocess.CalledProcessError):
        return {
            "source_commit": None,
            "source_worktree_dirty": None,
            "tracked_diff_hash": None,
            "release_eligible_source": False,
        }
    untracked_source_suffixes = {
        ".py",
        ".pyi",
        ".sh",
        ".toml",
        ".yaml",
        ".yml",
        ".json",
        ".json5",
        ".ini",
        ".cfg",
    }
    ignored_data_roots = ("data/", "artifacts/", "outputs/", "diagonostic/")
    untracked_source_files = []
    for line in untracked_status:
        if not line.startswith("?? "):
            continue
        relative = line[3:].strip()
        if relative.startswith(ignored_data_roots):
            continue
        if Path(relative).suffix.lower() in untracked_source_suffixes:
            untracked_source_files.append(relative)
    dirty = bool(status.strip()) or bool(untracked_source_files)
    return {
        "source_commit": commit or None,
        "source_worktree_dirty": dirty,
        "tracked_diff_hash": hashlib.sha256(tracked_diff).hexdigest(),
        "untracked_source_files": sorted(untracked_source_files),
        "release_eligible_source": bool(commit) and not dirty,
    }


def tool_schema_hashes(rows: Sequence[Mapping[str, Any]]) -> list[str]:
    return sorted(
        {
            stable_json_sha256(row.get("tools"))
            for row in rows
            if isinstance(row.get("tools"), list)
        }
    )


def build_gate_provenance(
    *,
    repo_root: str | Path,
    processor_revision: str,
    datasets: Mapping[str, str | Path],
    rows: Sequence[Mapping[str, Any]],
    exporter_files: Sequence[str | Path],
) -> dict[str, Any]:
    """Describe the source, schemas, exporter, processor, and exact datasets."""
    schema_hashes = tool_schema_hashes(rows)
    payload: dict[str, Any] = {
        **git_source_state(repo_root),
        "processor_revision": processor_revision,
        "schema_registry_hash": schema_hashes[0] if len(schema_hashes) == 1 else None,
        "schema_registry_hashes": schema_hashes,
        "exporter_hashes": {
            str(Path(path).resolve().relative_to(Path(repo_root).resolve())): file_sha256(path)
            for path in exporter_files
        },
        "dataset_hashes": {
            name: file_sha256(path) for name, path in sorted(datasets.items())
        },
    }
    return payload


def validate_generation_provenance(
    *,
    repo_root: str | Path,
    datasets: Mapping[str, str | Path],
    rows: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Verify that split files were generated by the current clean source tree."""
    failures: list[str] = []
    parents = {Path(path).resolve().parent for path in datasets.values()}
    if len(parents) != 1:
        failures.append("Dataset splits do not share one provenance directory.")
        provenance_path = None
    else:
        provenance_path = next(iter(parents)) / "aggregate.generation_provenance.json"
    payload: dict[str, Any] = {}
    if provenance_path is None or not provenance_path.is_file():
        failures.append("aggregate.generation_provenance.json is missing.")
    else:
        try:
            decoded = json.loads(provenance_path.read_text(encoding="utf-8"))
            payload = decoded if isinstance(decoded, dict) else {}
        except (OSError, json.JSONDecodeError) as exc:
            failures.append(f"Generation provenance is unreadable: {type(exc).__name__}: {exc}")
    current_source = git_source_state(repo_root)
    if not current_source.get("release_eligible_source"):
        failures.append("Current source worktree is not release eligible.")
    if payload:
        if payload.get("release_eligible") is not True:
            failures.append("Dataset generation provenance is not release eligible.")
        descriptor = payload.get("generation_descriptor")
        descriptor = descriptor if isinstance(descriptor, Mapping) else {}
        expected_id = payload.get("generation_provenance_id")
        if not descriptor or stable_json_sha256(descriptor) != expected_id:
            failures.append("Generation provenance identifier is invalid.")
        generated_source = descriptor.get("source_state")
        generated_source = generated_source if isinstance(generated_source, Mapping) else {}
        if generated_source.get("release_eligible_source") is not True:
            failures.append("Dataset was generated from a non-release source worktree.")
        if generated_source.get("source_commit") != current_source.get("source_commit"):
            failures.append("Dataset source commit does not match the current gate commit.")
        generator_hashes = descriptor.get("generator_hashes")
        generator_hashes = (
            generator_hashes if isinstance(generator_hashes, Mapping) else {}
        )
        if not generator_hashes:
            failures.append("Generation provenance has no generator/exporter hashes.")
        for relative, expected_hash in sorted(generator_hashes.items()):
            source_path = Path(repo_root) / str(relative)
            if not source_path.is_file() or file_sha256(source_path) != expected_hash:
                failures.append(
                    f"Generator/exporter source hash mismatch for {relative}."
                )
        row_ids = {row.get("generation_provenance_id") for row in rows}
        if not expected_id or row_ids != {expected_id}:
            failures.append(
                "Rows do not all bind to the generation provenance identifier."
            )
        recorded_hashes = payload.get("dataset_hashes")
        recorded_hashes = recorded_hashes if isinstance(recorded_hashes, Mapping) else {}
        for path in datasets.values():
            filename = Path(path).name
            expected_hash = recorded_hashes.get(filename)
            if expected_hash != file_sha256(path):
                failures.append(f"Dataset hash mismatch or missing provenance for {filename}.")
        schema_hashes = tool_schema_hashes(rows)
        if schema_hashes != [descriptor.get("schema_registry_hash")]:
            failures.append("Row tool schemas do not match generation provenance.")
    return {
        "passed": not failures,
        "failures": failures,
        "provenance_path": str(provenance_path) if provenance_path is not None else None,
        "generation_provenance_id": payload.get("generation_provenance_id"),
        "source_commit": (payload.get("source_state") or {}).get("source_commit")
        if isinstance(payload.get("source_state"), Mapping)
        else None,
        "release_eligible": payload.get("release_eligible") is True and not failures,
    }


__all__ = [
    "build_gate_provenance",
    "file_sha256",
    "git_source_state",
    "stable_json_sha256",
    "tool_schema_hashes",
    "validate_generation_provenance",
]
